name: 'Setup Flutter'
description: 'Setup Flutter and get dependencies'

inputs:
  flutter-version:
    description: 'Flutter version'
    required: false
    default: '3.38.1'
  new-version:
    description: 'New version to update in pubspec.yaml'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: 'stable'
        cache: true

    - name: Get dependencies
      shell: bash
      run: flutter pub get

    - name: Update version
      shell: bash
      run: |
        NEW_VERSION="${{ inputs.new-version }}"
        if [[ "$OSTYPE" == "darwin"* ]]; then
          sed -i '' "s/^version: .*/version: $NEW_VERSION/" pubspec.yaml
        else
          sed -i "s/^version: .*/version: $NEW_VERSION/" pubspec.yaml
        fi
